# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04-fr

---
- name: Configure master docker swarm node
  hosts: master
  become: yes

  tasks:

  - name: Setting docker-compose url
    set_fact:
      uname_s: "{{ lookup('pipe', 'uname -s') }}"
      uname_m: "{{ lookup('pipe', 'uname -m') }}"
  
  - debug: msg='uname_s {{ uname_s }} uname_m {{ uname_m }} '

  - name: Download docker-compose to bin folder
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ uname_s }}-{{ uname_m }}"
      dest: /usr/local/bin/docker-compose

  - name: Changing perm of "/usr/local/bin/docker-compose", adding "+x"
    file: dest=/usr/local/bin/docker-compose mode=a+x
