# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04-fr
# https://docs.docker.com/engine/install/ubuntu/

---
- name: Playbook
  hosts: all
  become: yes
  tasks:

  # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
  - name: Update server
    apt:
      update_cache: yes

  # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
  - name: Install dependecies for docker
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      state: present

  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
  - name: Add an Apt signing key, uses whichever key is at the URL
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
  - name: Add docker source repository into sources list
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
  - name: Update server
    apt:
      update_cache: yes

  # https://docs.ansible.com/ansible/2.9/modules/apt_module.html#apt-module
  - name: Install docker-ce
    apt:
      name: docker-ce
      update_cache: yes
      autoclean: yes
      autoremove: yes
      state: present

  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
  - name: Add the user 'vagrant' with a bash shell, appending the group 'docker' group
    ansible.builtin.user:
      name: vagrant
      shell: /bin/bash
      groups: docker
      append: yes